### ISSUE TITLE
errors when run "docker build"

### ISSUE THREAD

**Issue by dvector89** [jniehues-kit/SLT.KIT#1]
When I ran the command `sudo docker build --build-arg CUDA=9.1 -t slt.kit -f Dockerfile.ST-Baseline .` . I got the following errors. Is anyone can help me? Thanks advance.

`Step 21/27 : RUN ./Anaconda3*.sh -b
 ---> Using cache
 ---> 88820216d6b7
Step 22/27 : RUN /root/anaconda3/bin/pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -U docker-compose --upgrade pip
 ---> Running in 327362aed1b4
Collecting docker-compose
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/27/3c/6fcaa3b546ae8103c444149a1746f9a7043df7503e12bad318e8217312fb/docker_compose-1.21.2-py2.py3-none-any.whl (123kB)
Collecting pip
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl (1.3MB)
Collecting docopt<0.7,>=0.6.1 (from docker-compose)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Requirement already up-to-date: six<2,>=1.3.0 in /root/anaconda3/lib/python3.6/site-packages (from docker-compose)
Collecting cached-property<2,>=1.2.0 (from docker-compose)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ca/21/d793828ce0bb01baa6bed307c68466829343cc93fccc055cfbc21f774959/cached_property-1.4.2-py2.py3-none-any.whl
Collecting dockerpty<0.5,>=0.4.1 (from docker-compose)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/8d/ee/e9ecce4c32204a6738e0a5d5883d3413794d7498fe8b06f44becc028d3ba/dockerpty-0.4.1.tar.gz
Requirement already up-to-date: requests!=2.11.0,!=2.12.2,!=2.18.0,<2.19,>=2.6.1 in /root/anaconda3/lib/python3.6/site-packages (from docker-compose)
Collecting docker<4.0,>=3.3.0 (from docker-compose)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/31/01/41f727a549abd788eb91d0df4c801cb4c1f5227eee04a2621e13d7ed3e04/docker-3.3.0-py2.py3-none-any.whl (124kB)
Collecting texttable<0.10,>=0.9.0 (from docker-compose)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/02/e1/2565e6b842de7945af0555167d33acfc8a615584ef7abd30d1eae00a4d80/texttable-0.9.1.tar.gz
Requirement already up-to-date: jsonschema<3,>=2.5.1 in /root/anaconda3/lib/python3.6/site-packages (from docker-compose)
Collecting websocket-client<1.0,>=0.32.0 (from docker-compose)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/9d/fb/f51a03e232e00d6c504dfe815aed090c894ba3f8d3f7fd9612f3e227bf24/websocket_client-0.47.0-py2.py3-none-any.whl (200kB)
Requirement already up-to-date: PyYAML<4,>=3.10 in /root/anaconda3/lib/python3.6/site-packages (from docker-compose)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /root/anaconda3/lib/python3.6/site-packages (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.19,>=2.6.1->docker-compose)
Requirement already up-to-date: idna<2.7,>=2.5 in /root/anaconda3/lib/python3.6/site-packages (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.19,>=2.6.1->docker-compose)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /root/anaconda3/lib/python3.6/site-packages (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.19,>=2.6.1->docker-compose)
Collecting certifi>=2017.4.17 (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.19,>=2.6.1->docker-compose)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl (150kB)
Collecting docker-pycreds>=0.2.3 (from docker<4.0,>=3.3.0->docker-compose)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/5c/b6/3a4ca03225f6e9a25cb47cd3c695d19b88df5928ab9310e64dec1eb3b4d1/docker_pycreds-0.2.3-py2.py3-none-any.whl
Building wheels for collected packages: docopt, dockerpty, texttable
  Running setup.py bdist_wheel for docopt: started
  Running setup.py bdist_wheel for docopt: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/c2/fd/5c/ae35c7ac1c1398c2c32876413b11253743c82739b846ca94a7
  Running setup.py bdist_wheel for dockerpty: started
  Running setup.py bdist_wheel for dockerpty: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/4e/6b/c4/181696651db8b398af20329fdd405a698c428318e4d3ade20b
  Running setup.py bdist_wheel for texttable: started
  Running setup.py bdist_wheel for texttable: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/34/f6/b7/a55751713f982ebc8a12e21ebb3879c7ff9b0ba9680ba5e839
Successfully built docopt dockerpty texttable
Installing collected packages: docopt, cached-property, dockerpty, websocket-client, docker-pycreds, docker, texttable, docker-compose, pip, certifi
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
Exception:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/root/anaconda3/lib/python3.6/site-packages/pip' -> '/tmp/pip-1gclpbxp-uninstall/root/anaconda3/lib/python3.6/site-packages/pip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/root/anaconda3/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/root/anaconda3/lib/python3.6/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/root/anaconda3/lib/python3.6/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/root/anaconda3/lib/python3.6/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/root/anaconda3/lib/python3.6/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 556, in move
    rmtree(src)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 422, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 420, in _rmtree_safe_fd
    os.rmdir(name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: '__pycache__'
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c /root/anaconda3/bin/pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -U docker-compose --upgrade pip' returned a non-zero code: 2
`

**Comment by jniehues-kit** [comment]
Sorry, but currently, I cannot reproduce your error.
The first thing I noticed is that you run a different comment according to the log file than in the orignial docker file.
You have RUN /root/anaconda3/bin/pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -U docker-compose --upgrade pip
While in the original Docker file it is 
/root/anaconda3/bin/pip install --upgrade pip
Did you change the Docker file?
Otherwise, can you build the docker container only until the commands before this command and then run the last command interactively? Is the same error happening?

**Comment by dvector89** [comment]
Thanks very much.
**First, I ran the Docker file without modification. The errors are as follows:**

Step 13/27 : RUN cd /opt &&     git clone https://github.com/rsennrich/subword-nmt.git
 ---> Using cache
 ---> 34c855d8ca2a
Step 14/27 : RUN cd /opt &&     wget http://www.cs.umd.edu/%7Esnover/tercom/tercom-0.7.25.tgz &&     tar xfvz tercom-0.7.25.tgz
 ---> Using cache
 ---> 15b5ff6030d8
Step 15/27 : RUN cd /opt && wget https://raw.githubusercontent.com/stanojevic/beer/master/packaged/beer_2.0.tar.gz && tar xfvz beer_2.0.tar.gz
 ---> Running in 5230c162de2d
--2018-06-14 03:12:05--  https://raw.githubusercontent.com/stanojevic/beer/master/packaged/beer_2.0.tar.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.228.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.228.133|:443... connected.
ERROR: cannot verify raw.githubusercontent.com's certificate, issued by 'CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US':
  Unable to locally verify the issuer's authority.
To connect to raw.githubusercontent.com insecurely, use `--no-check-certificate'.
The command '/bin/sh -c cd /opt && wget https://raw.githubusercontent.com/stanojevic/beer/master/packaged/beer_2.0.tar.gz && tar xfvz beer_2.0.tar.gz' returned a non-zero code: 5

**Second, I added "--no-check-certificate" when using "wget". The errors are as follows:**

Step 20/27 : RUN chmod 755 Anaconda3*.sh
 ---> Using cache
 ---> 3c6351df5272
Step 21/27 : RUN ./Anaconda3*.sh -b
 ---> Using cache
 ---> 88820216d6b7
Step 22/27 : RUN /root/anaconda3/bin/pip install --upgrade pip
 ---> Running in f25a22e09827
Collecting pip
  Using cached https://files.pythonhosted.org/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
Exception:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/root/anaconda3/lib/python3.6/site-packages/pip' -> '/tmp/pip-02xpsxrz-uninstall/root/anaconda3/lib/python3.6/site-packages/pip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/root/anaconda3/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/root/anaconda3/lib/python3.6/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/root/anaconda3/lib/python3.6/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/root/anaconda3/lib/python3.6/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/root/anaconda3/lib/python3.6/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 556, in move
    rmtree(src)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 422, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 420, in _rmtree_safe_fd
    os.rmdir(name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: '__pycache__'
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c /root/anaconda3/bin/pip install --upgrade pip' returned a non-zero code: 2

**Third, I changed the 41st line to "RUN /root/anaconda3/bin/pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple". The errors are as follows:**

Step 21/27 : RUN ./Anaconda3*.sh -b
 ---> Using cache
 ---> 88820216d6b7
Step 22/27 : RUN /root/anaconda3/bin/pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple
 ---> Running in c5fc7facd32c
Collecting pip
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl (1.3MB)
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
Exception:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/root/anaconda3/lib/python3.6/site-packages/pip' -> '/tmp/pip-joez29jb-uninstall/root/anaconda3/lib/python3.6/site-packages/pip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/root/anaconda3/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/root/anaconda3/lib/python3.6/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/root/anaconda3/lib/python3.6/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/root/anaconda3/lib/python3.6/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/root/anaconda3/lib/python3.6/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 556, in move
    rmtree(src)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 422, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 420, in _rmtree_safe_fd
    os.rmdir(name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: '__pycache__'
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c /root/anaconda3/bin/pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple' returned a non-zero code: 2

I am not familiar with Docker. I ran it with the command: "sudo docker build --build-arg CUDA=9.1 -t slt.kit -f Dockerfile.ST-Baseline ." 
I don't know if there was any mistake while I ran the command.
Thanks.
